redpwn/rctf

.env.example
README.md
config/index.js
package.json
server/auth/token.js

Two small quality of life updates. 
1. Configure `yarn migrate` to use `RCTF_DATABASE_URL`
2. Switch `APP_TOKEN_KEY` to `RCTF_TOKEN_KEY` as per @ginkoid naming conventions. Also moved token key to config to be more declarative

Small environmental variable changes

---

install/install.sh

* use `--noconfirm` in pacman to avoid requirement for user input
* use `--needed` in pacman to not reinstall packages if up to date
* add `-y` in pacman to refresh package listing before installing dependencies
* add `apt-get update` in apt to refresh package listing before installing dependencies
* silence errors involving systemctl and masked units (docker is masked by default on Debian-like distros)
* have install script fix .env permissions automatically

Improve install script

---

app.js
package.json
yarn.lock

Simple quality of life PR, use `TEST_COMPRESSION=1 yarn dev` to run with compression to see true bundle sizes.

Added flag for compression

---

.travis.yml

Environment variables were mistakenly being set under the "global" key in "env"; fix this and remove the extraneous key

Fix environment variables not being set correctly

---

server/api/auth/recover.js
server/api/auth/register.js
server/api/submitflag.js
server/auth/register.js
test/_util.js
test/integration/challenges.js
test/integration/profile.js
test/integration/submit.js
test/integration/submitTiming.js

We updated to uuid@7, which deprecated the deep import syntax. Switch all imports to use the new factored import syntax.

Use factored import for uuid over deprecated import syntax

---

.nycrc.json

Switch nyc config to explicitly include files to include in coverage, instead of excluding most of the repository

Whitelist files to include in coverage instead of blacklisting

---

.eslintrc.js
package.json
server/.eslintrc.js
test/.eslintrc.js

Add back root eslintrc enforcing standard style and other project-wide options, make server/ eslintrc add typescript plugins only, and move ava plugin to test/.eslintrc.js
Also drop unused global definitions

Refactor eslint config

---

package.json
server/.eslintrc.js
server/util/normalize.ts
server/util/scores.ts
yarn.lock

ESLint server config was previously not using typescript rules for typescript, fix config to enable typescript rules for typescript files only, and enforce rules.
Also fix server/util/normlalize.ts not exporting its methods via ES6 exports, which causes tsc to not recognize its exports.

Fix ESLint TypeScript configs and exports

---

client/src/api/scoreboard.js
client/src/api/util.js

Refactor `request()` to automatically put the contents of `data` into the querystring of a request if the request method is `GET`. This implementation currently will add extraneous `?`s to the request URL
when no querystring parameters are provided, however it appears that it is stripped off by the browser.

Allow querystring parameters as an object in request

---

client/.eslintrc.js
client/src/api/auth.js
client/src/pages/challenges.js
client/src/pages/logout.js
client/src/pages/profile.js

The eslint preact config currently overrides style rules (see preactjs/eslint-config-preact#6), so override that by loading the standard config again.

Ensure standard rules are enforced

---

client/src/pages/scoreboard.js

If the user's team is not on the current scoreboard page, defer the attempt to scroll it into view until the data for the scoreboard page the user is on is actually loaded.
A possible optimization for this is to scroll to the element where the user's team "would" be located on the scoreboard before the data has loaded, however that would require us to reuse the host elements in the table when the scoreboard page changes.
Fixes #119

Defer attempt to scroll to own team on scoreboard until the user's team's scoreboard page is loaded

---

client/src/components/modal.js
client/src/pages/profile.js

Add modal component using Cirrus's modals (with manual animations, since Cirrus relies on using the URI hash to show/hide modals), and use it to implement confirmation for deleting accounts instead of `prompt()`
Closes #74

Add modal for confirming account deletion

---

client/src/pages/profile.js

Fix account deletion dialog's `modal-body` being inside of its `modal-header`, and adjusted styles to reduce unnecessary padding between elements of the dialog.
New dialog:
Old dialog:

Restyle account deletion dialog

---

client/src/pages/profile.js

Event handler for controlled `input` element in the form in the account deletion dialog for confirming team name used the wrong event (`onChange` only fires when the user is done editing rather than as they are typing). Fix this so that the "Confirm" button will reactivate as soon as the correct team name is typed in the dialog.

Make account deletion dialog update when you type

---

.eslintrc.js
client/.eslintrc.js
client/src/components/header.js
server/util/index.js

Until we can stop re-including standard in the client config due to preact's style configs accidentally being included, the rule needs to be redeclared in the client eslintrc since loading standard clears the BOF option.

Enforce no blank lines at beginning of file

---

.travis.yml

Run linting in a separate job. Also pulled out node environment config into an anchor to enable reuse across multiple node jobs.
Other fixes:
- `redis-server` is an alias for `redis`, so use `redis`
- Fix `node_js` being incorrectly specified as an array

Split linting out to a separate job

---

package.json

Allow for overwriting of files so that changes to configuration (e.g. `.rdeploy`, `config/server.js`) are properly updated in dist/ when it is used by the server.

fix(build): overwrite files when copying static files

---

migrations/1581725957097_del-password.js
migrations/1582424634372_string-uuids.js
migrations/1585799727940_add-ctftime-id.js

Ensure that irreversible migrations are marked as such, that type conversions are implemented correctly, and that the changes are executed in the right order.

fix: make migrate down work on migrations

---

client/src/components/ctftime-button.js
client/src/components/or.js
client/src/routes/login.js
client/src/routes/registration.js

Use Spotify-style or with dividing line between token / email login / signup and ctftime OAuth button.

feat(client): restyle or divider in login / register

---

client/lib/svg-icon-component-generator.js
client/src/components/graph.js
package.json

Fix:
- unnecessary argument in svg-sprite-loader runtime generator
- `copy-static` script no longer overwrites `tsc` output for plain JS
- improvements to the graph line hover region

Small cleanup fixes

---

Dockerfile

Clear yarn caches in docker build. Also use `--frozen-lockfile` flag to ensure lockfile consistency, and explicit `--prod` flag.
Image reduced to ~13MB own size

fix(build): remove yarn caches from docker images

---

client/lib/loaders/mustache-rendered-loader.js
preact.config.js

When in dev mode, render the Mustache templates in `index.html` within Webpack; this fixes `yarn dev`.
Currently the context for the mustache template is copy-pasted from the server rendering code.

Render mustache in WDS (yarn dev)

---

client/src/api/profile.js

Fixed updateAccount sending `null` for `division`, creating an invalid request,  when no division was provided to the function.

fix(client): fix updateAccount sending invalid payload

---

preact.config.js

Require client config in preact build only when running in dev mode. This allows the container to be built without needing to have a client config present.

fix(build): only require client config when needed

---

server/app.js
server/util/index.js

Since Fastify does not have any hooks that run before the request is logged, we have to override the request serializer to modify `req.ip` in the logged request data. We also register a hook as early as possible to modify the real `req.ip`. The serializer is copied from the default implemenation in Fastify.

feat(server): parse real IP from Cloudflare headers

---

preact.config.js

This uses regex to find and remove the rules for copying preact-cli's default manifest.json and associated icon; this may require updating if preact-cli changes how the manifest is created.

fix(client): remove preact-cli's manifest.json

---

package.json

Tell nodemon to ignore everything except for tsc build outputs used by the server.

fix: prevent nodemon from reloading unless server changes

---

client/src/components/markdown.js
client/src/components/problem.js

Add `target="_blank"` attribute to all links in challenge Markdown description.

feat(client): open challenge links in new tab

---

client/src/routes/challs.js
client/src/routes/scoreboard.js

Use localstorage to save "preferences" (division + page size), and use query string parameters to make absolute links to scoreboard pages (which includes division and page size). The query string is updated if the current scoreboard page is not 1, or there previously was a query string.

feat(client): save scoreboard settings on client

---

server/api/admin/upload/post.js
server/responses/index.js

The current implementation of the file upload endpoint does not distinguish between errors from the upload provider, and errors from a malformed data URI provided by the user (see #300).
This commit changes the behavior of the file upload endpoint to convert the data URIs synchronously first, returning a status code of 400 and an appropriate error if any data URI conversion fails.
This commit also updates the message for a failed upload that failed for reasons other than a user error.
fix #300

fix(server): add error message for malformed data uris

---

client/src/routes/challs.js

Have a separate state for `problems` when data has not loaded to
differentiate between no challenges existing and data not yet loaded.
Bug found by @DarinMao

fix(client): fix fetch loop when no challenges exist

---

package.json

Use strict unhandled promise rejections (like in Dockerfile) in `yarn start`, and drop unnecessary use of `sh` in `yarn migrate`.

fix: clean up package.json scripts

---

docs/content/configuration.md
server/app.js
server/config/server.ts
server/util/index.ts

Add configurable setting for trusting `Cf-Connecting-Ip` header and `X-Forwarded-For` parsing.
Closes #430

feat(server): add config option for proxy trust

---

.github/workflows/ci.yml
CONTRIBUTING.md
scripts/check-commits.sh

Add script to run in CI on pull request to enforce commit message summary lines match the conventions specified in CONTRIBUTING.md.
Also update outdated branch names in CONTRIBUTING.md

ci: enforce commit message conventions

---

docs/content/management/home.md

Added description about the options that were missing.
Cherry-picked and squashed from PR #520 (originally created by @pr0PM)

docs: add docs for sponsors cards

---

.github/workflows/ci.yml

Docker images use node 14, so update CI jobs to match.

ci: update node to 14

---

packages/server/src/api/helpers.ts
packages/server/src/api/leaderboard/graph.ts
packages/server/src/api/users/util.ts

When getting the element type of an array type, use `Type[number]` where applicable. One instance of `ArrayValue` in database/util.ts was kept to work with the type potentially not being an array.

refactor(server): clean up getting array element types

---

packages/server/src/cache/leaderboard.ts

Small refactor of implementation of leaderboard cache `getRange` to leverage type narrowing on the range parameters to eliminate a pair of casts. Also restrict the `all` parameter to `true` only.

refactor(server): leverage narrowing on cache typing

---

packages/server/src/leaderboard/calculate.ts
packages/server/src/leaderboard/types.ts
packages/server/test/unit/leaderboard/__snapshots__/calculate.ts.snap
packages/server/test/unit/leaderboard/calculate.ts

Backports changes from #543
Also adjusted types at the module boundary of the leaderboard worker code to hide implementation detail data.
This change also strips the data from the objects, resulting in the creation of a new JS object per leaderboard entry, but keeps snapshots cleaner. We may wish to consider doing this in only snapshot serialization in the future.

chore: backport ranking users with only tiebreakEligible: false

---

docs/content/providers/uploads/gcs.md

https://github.com/redpwn/rctf/blob/0f05c62e45c565fa4873e264656dd74d4e3ec833/server/providers/uploads/gcs/index.ts#L17

Fix typo in GCS docs
