redpwn/rctf

- migrations/1581292018019_add-users.js
- migrations/1581292025458_user-perms.js
- server/database/auth.js
Added `perms` to user table and updated respective authorization db functions.
> Added perms column to users

- .gitignore
- README.md
- config/index.js
- server/challenges/index.js
- server/util/index.js
Finished integration of challenge data exports with `server/challenges`
> Challenge data integration

- .gitignore
- .nycrc.json
- package.json
- test/unit/challenges.js
- yarn.lock
Setup basic testing environment with nyc and ava
> Added testing framework

- server/api/auth-login.js
- server/api/index.js
- server/api/submitflag.js
- server/responses/index.js
Refactored `routes.schema` into `routes.schema.body` and `routes.schema.params` for more specific validations
> Improved schema validations

- server/api/leaderboard.js
- test/unit/util.js
Modified how leaderboard accesses getScore
> Added tests for util/score

- server/database/solves.js
- test/integration/submitflag.js
- yarn.lock
Assumes challenges is filled with at least one element. I'm not sure how to change the information of challenges without using NODE_ENV.
> Added tests for submitflag

- config/index.js
- server/api/auth-submit.js
- server/api/auth-test.js
- server/api/auth-verify.js
- server/api/index.js
- server/database/auth.js
- server/responses/index.js
- test/integration/auth.js
- test/integration/leaderboard.js
- test/integration/submitflag.js
- yarn.lock
Also added `config.verifyEmail` to configure if emails should be sent. If not, the response will be identical to as if you posted the token to `/verify`
> Added auth tests

- app.js
- client/src/api/auth.js
- client/src/api/index.js
- client/src/components/registration.js
- client/src/config.js
- config/index.js
- package.json
- yarn.lock
When email verification is off, put the returned tokens into localStorage.
> Finished registration javascript

- .env.example
- README.md
- install/install.sh
TODO sometime in the future:
* run docker-compose not as root?
* support RHEL derivative distributions
> Add installation script for Debian-based distros and Arch Linux

- server/api/auth-submit.js
- server/api/auth-verify.js
- server/database/auth.js
- server/leaderboard/calculate.js
- server/responses/index.js
- server/util/auth.js
- server/util/index.js
Added check if score is 0 for leaderboard
> Added more detailed errors to auth, fixed leaderboard

- app.js
- client/src/api/auth.js
- client/src/config.js
- client/src/index.js
- client/src/pages/index.js
- client/src/pages/profile.js
> Added /profile frontend

- .nycrc.json
- .travis.yml
- client/src/api/scoreboard.js
- client/src/index.js
- client/src/pages/challenges.js
- client/src/pages/index.js
- client/src/pages/profile.js
- client/src/pages/scoreboard.js
- package.json
> Added leaderboard frontend

- client/src/api/profile.js
- client/src/index.js
- client/src/pages/profile.js
Currently does not work because `/api/v1/users/:uuid` is not implemented, but once the API is up the pages will become accessible at `/profile/:uuid`.
> Added public profile pages

- client/src/api/challenges.js
- client/src/pages/profile.js
- migrations/1582424634372_string-uuids.js
- server/api/auth/test.js
- server/api/submitflag.js
- server/api/users/id.js
- server/api/users/me.js
- server/api/users/util.js
- server/cache/leaderboard.js
- server/leaderboard/calculate.js
- server/responses/index.js
- test/integration/auth.js
- test/integration/submit.js
also includes a bunch of small bug fixes
> migrate to use strings for uuids in postgres

- client/src/pages/challenges.js
- migrations/1582446586521_foreign-key-userid.js
- server/api/users/delete.js
- server/api/users/index.js
- server/api/users/update.js
- server/database/auth.js
- server/responses/index.js
- test/integration/auth.js
- test/integration/submit.js
- test/util.js
Implemented PATCH and DELETE on `/users/me`
> Users api functions

- client/src/api/challenges.js
- client/src/index.js
- client/src/pages/challenges.js
- client/src/util/index.js
- client/src/util/toasts/Toast.js
- client/src/util/toasts/context.js
- client/src/util/toasts/index.js
- client/src/util/toasts/useToast.js
- client/src/util/toasts/withToastProvider.js
- server/api/users/index.js
- server/api/users/me-solves.js
Made show solved button functional.
Added global toasts.
Hides challenge on successful submit and displays toast.
> Improved challenges page

- client/src/api/auth.js
- client/src/index.js
- client/src/pages/error.js
- client/src/pages/home.js
- client/src/pages/index.js
- client/src/pages/login.js
- client/src/pages/verify.js
- test/integration/auth.js
Multiple small quality of life updates for frontend
1. Hide sponsor page when sponsors array length is zero
2. Removed non-generic sponsorship text one homepage
3. Added `/verify#token=` and `/login#token=` for automatic authentication
> Frontend Quality of Life Updates

- .travis.yml
- client/build.sh
Run shellcheck in CI to lint all shell scripts for issues and POSIX compliance
Currently, the shellcheck job is failing, however these issues should be fixed by #88
> Add shellcheck CI job

- test/integration/challenges.js
- test/unit/rateLimit.js
Ensure tests are importing from `dist/server/` and not `server/`
> Import transpiled files in tests

- client/src/index.js
- client/src/pages/scoreboard.js
- server/api/users/me.js
Resolves https://github.com/redpwn/rctf/issues/109
> Highlight own team scoreboard

- client/src/routes/profile.js
Profile page has been broken up into smaller components and refactored to use hooks and function components instead of class components.
> Use hooks in Profile page

- client/src/api/challenges.js
- server/api/users/util.js
Resolves https://github.com/redpwn/rctf/issues/132
Switched to challenge javascript api to load from `/api/users/me` for consistency.
> Fix missing route error

- client/src/routes/challenges.js
- client/src/routes/home.js
- client/src/routes/login.js
- client/src/routes/profile.js
- client/src/routes/registration.js
- client/src/routes/scoreboard.js
- client/src/routes/sponsors.js
- convert px to em
- fix a couple padding issues in tiles
- fix capitalization in titles
- add profile page UI improvements from #142
> UI improvements

- client/index.html
- client/src/components/graph.js
- client/src/routes/challenges.js
- client/src/routes/home.js
- client/src/routes/login.js
- client/src/routes/registration.js
- client/src/routes/scoreboard.js
- config/client.js.example
- package.json
- preact.config.js
- server/app.js
- yarn.lock
Restyled the graph and other small changes to make frontend cleaner.
> Cleanup frontend

- .dockerignore
- .rdeploy.example/config.json
- .rdeploy.example/files/example-sha1hash.txt
- .rdeploy.example/files/example1.txt
- .rdeploy.example/files/example2.txt
- .rdeploy.example/files/example3.txt
- Dockerfile
- config/server.js
The new dockerfile works with K8S.
> feat(docker): add new multistage dockerfile build

- client/src/api/challenges.js
- client/src/api/profile.js
- client/src/api/util.js
- client/src/components/problem.js
- client/src/routes/challs.js
- client/src/routes/profile.js
- client/src/routes/scoreboard.js
- server/api/admin/challs/get.js
- server/api/users/util.js
- server/challenges/util.ts
- server/providers/challenges/database/index.ts
- server/responses/index.js
- server/util/index.js
Bundled a lot of small bug fixes into this PR
> Multiple bug fixes

- client/src/components/footer.js
- client/src/index.js
> feat(client): add footer with link to rCTF

- .lintstagedrc.js
- package.json
- yarn.lock
> chore: use lint-staged in pre-commit hook

- config/server.js
- server/api/admin/upload.js
- server/providers/challenges/rdeploy-blob/index.ts
Fix upload endpoint not providing file name, wrong data
type in SQL config, and a missing function call.
Cherry-picked from e97e5ca0
> fix(server): small bug fixes

- package.json
- server/util/index.ts
- server/util/perms.js
- server/util/perms.ts
- server/util/validate.ts
- yarn.lock
Removed reloadModule from server/util/index since it is never used, and was originally only used by test code; if it is needed again, it should be included in the test/ tree.
> refactor(server): type server util files

- packages/client/src/__snapshots__/storyshots.test.ts.snap
- packages/client/src/components/card.stories.tsx
- packages/client/src/components/card.test.tsx
- packages/client/src/components/card.tsx
- packages/client/src/components/navbar.tsx
- packages/client/src/components/textinput.tsx
- packages/client/src/util/react-types.ts
- packages/client/src/util/theme.ts
> feat(client): add Card component

- .github/workflows/ci.yml
- CONTRIBUTING.md
- scripts/check-commits.sh
Backport pull request #522 from redpwn/ci/commit-check onto master
> ci: enforce commit message conventions

- yarn.lock
Run `yarn-deduplicate yarn.lock`
> build(deps): deduplicate yarn.lock

- README.md
- docs/content/index.md
- docs/content/management/divisions.md
Includes #555, #569, and other commits not in PRs.
> chore: cherry-pick changes from master
